'use strict';
const DAYS = [
 {title:'Ключ от студии',friend:'Фея Люми · хранительница зеркала',story:'В зеркале исчезли звёзды! Люми зовёт тебя зажечь свет и открыть первую волшебную студию.',mission:'Зажги звёздное зеркало',intro:'Звёзды живут группами. Две группы по пять — это 2 × 5. Сначала потренируемся вместе, потом ты соберёшь свой образ.',factors:[2,5,10],icon:'🪞',reward:'Зеркало Люми',end:'Зеркало снова сияет. Люми дарит тебе звёздный бант!',tip:'Умножить на 2 — удвоить. На 5 — считать пятёрками. На 10 — считать десятками.'},
 {title:'Камера облаков',friend:'Газан · сказочный оператор',story:'Газан потерял светлячков для камеры. Собери их в ряды — и камера снова сможет снимать волшебство.',mission:'Собери свет для камеры',intro:'Сегодня строим ряды по 3 и по 4. Поверни воображаемую картинку: 3 × 4 и 4 × 3 дают одинаковое число!',factors:[3,4],icon:'📷',reward:'Камера Газана',end:'Камера работает! Теперь Газан сможет снять твоё шоу.',tip:'3 × число — это двойное число и ещё одно такое. 4 × число — удвоить, а потом ещё раз удвоить.'},
 {title:'Портал Six Seven',friend:'Газан · сказочный ведущий ритма',story:'Перед студией возник портал 6×7. Его код — 42! Газан собирает ритм для твоего выступления.',mission:'Раскрой код портала',intro:'Six Seven напоминает нам о 6 и 7. Но умножение — это 6 групп по 7: всего 42. Найдём и другие секреты этих чисел.',factors:[6,7],icon:'🎤',reward:'Микрофон ритма',end:'Код 42 принят! Портал открылся, и микрофон ритма теперь твой.',tip:'6 × число = 5 × число + ещё одно такое число. 7 × число = 5 × число + 2 × число.'},
 {title:'Дракон и созвездия',friend:'Дракон Искорка · мастер света',story:'Искорка готовит звёздный потолок. Помоги собрать созвездия из восьмёрок и девяток.',mission:'Зажги большой небосвод',intro:'Большие числа можно разобрать на маленькие. 9 × 7 — это 10 × 7 минус 7. Попробуем вместе!',factors:[8,9],icon:'🐉',reward:'Дракон света',end:'Созвездия сияют! Искорка становится твоим помощником на сцене.',tip:'8 × число — трижды удвоить число. 9 × число — десять таких чисел минус одно.'},
 {title:'Репетиция волшебства',friend:'Вся команда · ты режиссёр!',story:'Зеркало, камера и свет готовы. Смешай все заклинания и помоги друзьям провести репетицию.',mission:'Собери знакомые заклинания',intro:'Сегодня встречаются все числа. Можно использовать подсказки: наша цель — разобраться и запомнить, а не торопиться.',factors:[2,3,4,5,6,7,8,9,10],icon:'👑',reward:'Корона режиссёра',end:'Репетиция удалась! Ты получаешь корону режиссёра.',tip:'Если забываешь пример, переставь числа местами или начни с знакомого произведения.'},
 {title:'Подарки поровну',friend:'Фея Люми и сказочный Газан',story:'После репетиции друзья получили подарки. Раздели их поровну, чтобы каждому досталось одинаково.',mission:'Подели подарки между друзьями',intro:'Умножение поможет делить! Если 6 × 7 = 42, то 42 ÷ 6 = 7 и 42 ÷ 7 = 6. Сегодня проверим эти связи.',factors:[2,3,4,5,6,7,8,9,10],division:true,icon:'🎁',reward:'Сундук подарков',end:'Все друзья получили подарки поровну. Сундук сюрпризов открыт!',tip:'При делении спроси: на какое число нужно умножить делитель, чтобы получить всё количество?'},
 {title:'Большое шоу 42',friend:'Газан и сказочная команда',story:'Сегодня премьера! Собери последние звёзды, выбери образ и запусти своё волшебное шоу.',mission:'Устрой премьеру недели',intro:'В финале перемешались умножение и деление. Каждый решённый пример добавляет свет на твою сцену.',factors:[2,3,4,5,6,7,8,9,10],mixed:true,icon:'🌟',reward:'Сцена мечты',end:'Премьера состоялась! Ты помогла всей команде и открыла свою студию 6×7.',tip:'Умножение собирает равные группы, а деление помогает разделить их поровну.'}
];
const KEY='vasilisa-studio-v1';
const fresh=()=>({version:1,stars:0,completed:[],facts:{},sessions:[],look:'✦',backdrop:'night',avatar:'img/vasilisa-toy-avatar.png'});
let state;try{state=JSON.parse(localStorage.getItem(KEY));if(!state||state.version!==1||!Array.isArray(state.completed)||!state.facts)state=fresh()}catch{state=fresh()}
if(typeof state.avatar==='string'&&state.avatar.startsWith('assets/'))state.avatar=state.avatar.replace('assets/','img/');
if(!state.avatar||state.avatar==='img/vasilisa-avatar.png')state.avatar='img/vasilisa-toy-avatar.png';
let selected= Math.min(6,Array.from({length:7},(_,i)=>i).find(i=>!state.completed.includes(i))??6), session=null, audioEnabled=false, audioContext=null, beatTimer=null, song=null, songUrl=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{$('starCount').title='Браузер не смог сохранить прогресс. Скачайте отчёт в разделе для взрослого.'}}
function keyOf(q){return `${q.div?'d':'m'}:${q.a}:${q.b}`}
function answer(q){return q.div?q.b:q.a*q.b}
function expression(q){return q.div?`${q.a*q.b} ÷ ${q.a}`:`${q.a} × ${q.b}`}
function shuffle(a){const items=[...a];for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function choicesFor(q){const correct=answer(q),values=new Set([correct]);for(const delta of [q.div?1:q.a,-(q.div?1:q.a),2,3,4]){if(correct+delta>=0)values.add(correct+delta);if(values.size===4)break}return shuffle([...values])}
function bank(day){return day.factors.flatMap(a=>Array.from({length:9},(_,i)=>({a,b:i+2,div:!!day.division}))).concat(day.mixed?day.factors.flatMap(a=>Array.from({length:9},(_,i)=>({a,b:i+2,div:true}))):[])}
function selectQueue(index){const pool=bank(DAYS[index]);const ranked=shuffle(pool).sort((a,b)=>{const score=q=>{const f=state.facts[keyOf(q)];return f?f.clean*2-f.errors*3:0};return score(a)-score(b)});let chosen=ranked.slice(0,12);if(index===2){chosen=chosen.filter(q=>!(q.a===6&&q.b===7)&&!(q.a===7&&q.b===6));chosen=[{a:6,b:7,div:false},{a:7,b:6,div:false},...chosen].slice(0,12)}if(index>0){const learned=Object.entries(state.facts).filter(([,f])=>f.errors>0).sort((a,b)=>b[1].errors-a[1].errors).slice(0,2).map(([key])=>{const [type,a,b]=key.split(':');return {a:+a,b:+b,div:type==='d'}});chosen.push(...learned)}return chosen}
function updateChrome(){const day=DAYS[selected];$('days').innerHTML=DAYS.map((d,i)=>`<button data-day="${i}" class="${i===selected?'active':''}" aria-current="${i===selected?'step':'false'}">${state.completed.includes(i)?'✓':i+1}<small>День ${i+1}</small></button>`).join('');$('days').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.day;session=null;renderIntro();});$('starCount').textContent=state.stars;$('chapterLabel').textContent=`ДЕНЬ ${selected+1} / 7`;$('chapterTitle').textContent=day.title;$('chapterStory').textContent=day.story;$('friend').textContent=day.friend;$('rewards').innerHTML=DAYS.map((d,i)=>`<div class="reward ${state.completed.includes(i)?'':'locked'}"><span>${state.completed.includes(i)?d.icon:'◇'}</span>${d.reward}</div>`).join('');$('look').innerHTML='<option value="✦">Звёздный</option>'+ (state.completed.includes(0)?'<option value="🎀">Бант Люми</option>':'')+(state.completed.includes(4)?'<option value="👑">Корона</option>':'');$('look').value=state.look;$('accessory').textContent=state.look;$('backdrop').value=state.backdrop;document.body.className=state.backdrop==='night'?'':state.backdrop+'-scene';if(state.avatar){$('avatar').src=state.avatar;$('avatar').hidden=false;$('avatarPlaceholder').hidden=true}}
function renderIntro(){updateChrome();const day=DAYS[selected];$('play').innerHTML=`<span class="pill">${state.completed.includes(selected)?'Можно пройти ещё раз':'12–14 заклинаний · без таймера'}</span><h2>${day.mission}</h2><p>${day.intro}</p><div class="helper"><b>Секрет дня</b><p>${day.tip}</p></div><p>Решай в своём темпе. Если трудно — друзья помогут.</p><div class="intro-actions"><button id="start" class="primary">${state.completed.includes(selected)?'Повторить приключение':'Начать приключение'}</button></div>`;$('start').onclick=startSession}
function startSession(){session={day:selected,queue:selectQueue(selected),index:0,errors:0,hints:0,clean:0,retry:[],started:Date.now(),attempts:0,helped:false,done:false,answered:false};renderQuestion()}
function renderQuestion(){const s=session;if(s.index>=s.queue.length){finish();return}const q=s.queue[s.index];s.attempts=0;s.helped=false;s.answered=false;const typed=selected>=4;const choices=choicesFor(q);$('play').innerHTML=`<span class="pill">${DAYS[selected].icon} ${q.div?'Подарки поровну':'Волшебные группы'}</span><div class="progress"><div style="width:${s.index/s.queue.length*100}%"></div></div><span class="eyebrow">ЗАКЛИНАНИЕ ${s.index+1} ИЗ ${s.queue.length}</span><p>${q.div?`Раздели ${q.a*q.b} звёзд поровну между ${q.a} друзьями. Сколько получит каждый?`:`Групп звёзд: ${q.a}. В каждой — ${q.b}. Сколько звёзд всего?`}</p><div class="equation">${expression(q)} = ?</div>${typed?'<form id="answerForm" class="entry"><input id="numberAnswer" type="text" inputmode="numeric" autocomplete="off" aria-label="Твой ответ" placeholder="Ответ"><button class="primary">Проверить</button></form>':`<div class="answers">${choices.map(n=>`<button data-answer="${n}">${n}</button>`).join('')}</div>`}<button id="hint" class="hint">✦ Покажи, как посчитать</button><div id="help"></div><div id="feedback" aria-live="polite"></div><button id="next" class="primary" hidden style="margin-top:18px">Продолжить</button>`;
 if(typed){$('answerForm').onsubmit=e=>{e.preventDefault();const value=$('numberAnswer').value.trim();if(!/^\d{1,3}$/.test(value)){$('feedback').innerHTML='<div class="feedback retry">Впиши целое число, например 42.</div>';return}checkAnswer(+value)}}else{$('play').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>checkAnswer(+b.dataset.answer))}
 $('hint').onclick=()=>showHint(q);$('next').onclick=()=>{s.index++;renderQuestion()};}
function showHint(q){if(session.answered)return;if(!session.helped)session.hints++;session.helped=true;let explanation;if(q.div){explanation=`Вспомним умножение: ${q.a} × ${q.b} = ${q.a*q.b}. Значит, ${q.a*q.b} ÷ ${q.a} = ${q.b}.`}else if(q.a>5){explanation=`Разобьём на знакомые группы: 5 × ${q.b} = ${5*q.b}. Ещё ${q.a-5} × ${q.b} = ${(q.a-5)*q.b}. Вместе ${5*q.b} + ${(q.a-5)*q.b} = ${q.a*q.b}.`}else{explanation=`${Array.from({length:q.a},()=>q.b).join(' + ')} = ${q.a*q.b}. ${q.a} одинаковых групп по ${q.b}.`}
 $('help').innerHTML=`<div class="helper"><div class="groups" aria-label="${q.a} групп по ${q.b} звёзд">${Array.from({length:q.a},()=>`<div class="group">${'★'.repeat(q.b)}</div>`).join('')}</div>${explanation}</div>`;}
function checkAnswer(n){const s=session;if(s.answered||s.done)return;const q=s.queue[s.index];const k=keyOf(q);state.facts[k]??={clean:0,errors:0,helped:0,last:0};const f=state.facts[k];if(n!==answer(q)){s.attempts++;s.errors++;f.errors++;f.last=Date.now();if(!s.retry.includes(k)&&s.queue.length<18){s.retry.push(k);s.queue.splice(Math.min(s.index+4,s.queue.length),0,{...q})}$('feedback').innerHTML='<div class="feedback retry">Пока не совпало. Посмотри на группы и попробуй ещё раз — ты справишься!</div>';showHint(q);save();return}
 s.answered=true;f.last=Date.now();if(!s.helped&&s.attempts===0){f.clean++;s.clean++}else f.helped++;save();$('feedback').innerHTML=`<div class="feedback good">✦ Получилось! ${expression(q)} = ${answer(q)}.${q.div?` Проверка: ${q.a} × ${q.b} = ${q.a*q.b}.`:''}</div>`;$('play').querySelectorAll('.answers button,.entry button,.entry input,#hint').forEach(el=>el.disabled=true);$('next').hidden=false;$('next').focus();playChime();}
function finish(){const s=session;if(s.done)return;s.done=true;const first=!state.completed.includes(selected);if(first){state.completed.push(selected);state.stars+=7}state.sessions.push({day:selected+1,date:new Date().toISOString(),questions:s.queue.length,clean:s.clean,errors:s.errors,hints:s.hints,seconds:Math.round((Date.now()-s.started)/1000)});save();updateChrome();const day=DAYS[selected];$('play').innerHTML=`<span class="pill">${day.icon} ${day.reward} ${first?'открыт!':'уже в коллекции'}</span><h2>${selected===6?'Твоя большая премьера!':'Маленькое чудо готово!'}</h2><p>${day.end}</p><div class="show" id="show"><img src="img/friends-v2.png" alt="Сказочная команда на сцене">${state.avatar?`<img id="showAvatar" src="${esc(state.avatar)}" alt="Василиса в кадре">`:''}</div><div class="stats"><span>✦ ${s.clean} без подсказок</span><span>♡ ${s.hints} с помощью друзей</span></div><p>${selected===6?'Неделя закончилась, а приключение может продолжаться. Повторяй дни и укрепляй свои заклинания.':'На сегодня достаточно. Следующее приключение ждёт тебя завтра — или когда захочешь.'}</p><div class="intro-actions"><button id="showBtn" class="pink">Снять волшебный клип</button><button id="continue" class="primary">${selected===6?'Вернуться к приключениям':'Посмотреть следующий день'}</button></div>`;$('showBtn').onclick=()=>{$('show').classList.toggle('running');$('showBtn').textContent=$('show').classList.contains('running')?'Остановить клип':'Снять волшебный клип';};$('continue').onclick=()=>{selected=selected===6?0:selected+1;session=null;renderIntro()}}
function playChime(){if(!audioEnabled||song)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();[523.25,659.25,783.99].forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.07;o.frequency.value=freq;g.gain.setValueAtTime(.025,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.2)})}catch{}}
async function toggleAudio(){if(audioEnabled){audioEnabled=false;clearInterval(beatTimer);beatTimer=null;song?.pause()}else{try{if(song){await song.play()}else{audioContext??=new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();let step=0;beatTimer=setInterval(()=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=[130.81,164.81,196,164.81][step++%4];g.gain.setValueAtTime(.018,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.15);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.18)},420)}audioEnabled=true}catch{$('musicStatus').textContent='Не удалось воспроизвести файл. Попробуйте другой аудиофайл.'}}$('sound').textContent=`♫ Звук: ${audioEnabled?'вкл.':'выкл.'}`}
function renderReport(){const troublesome=Object.entries(state.facts).filter(([,f])=>f.errors||f.helped).sort((a,b)=>(b[1].errors+b[1].helped)-(a[1].errors+a[1].helped)).slice(0,10);$('report').innerHTML=`<p><b>Пройдено ${state.completed.length} из 7 дней. Звёзд: ${state.stars}.</b></p><table><thead><tr><th>День</th><th>Попыток</th><th>Без помощи*</th></tr></thead><tbody>${DAYS.map((d,i)=>{const runs=state.sessions.filter(s=>s.day===i+1),last=runs.at(-1);return `<tr><td>${i+1}. ${d.title}</td><td>${runs.length}</td><td>${last?`${last.clean}/${last.questions}`:'—'}</td></tr>`}).join('')}</tbody></table><p>* Результат последнего прохождения. Это наблюдение за ответами, а не оценка усвоения всей таблицы.</p><h3>Что полезно повторить</h3><p>${troublesome.length?troublesome.map(([k])=>{const [t,a,b]=k.split(':');return expression({a:+a,b:+b,div:t==='d'})}).join(' · '):'Пока нет примеров с ошибками или подсказками.'}</p>`}
$('sound').onclick=toggleAudio;$('parent').onclick=()=>{renderReport();$('parentDialog').showModal()};$('closeParent').onclick=()=>$('parentDialog').close();$('look').onchange=e=>{state.look=e.target.value;save();updateChrome()};$('backdrop').onchange=e=>{state.backdrop=e.target.value;save();updateChrome()};
$('musicFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(audioEnabled)await toggleAudio();if(songUrl)URL.revokeObjectURL(songUrl);songUrl=URL.createObjectURL(file);song=new Audio(songUrl);song.loop=true;song.volume=.3;$('musicStatus').textContent=`Выбрана музыка: ${file.name}. Нажмите «Звук». Файл нужно выбрать заново после перезагрузки.`};
$('avatarFile').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>3*1024*1024){$('avatarStatus').textContent='Выберите изображение до 3 МБ.';return}const reader=new FileReader();reader.onload=()=>{state.avatar=reader.result;save();updateChrome();$('avatarStatus').textContent='Игрушечный аватар добавлен.'};reader.readAsDataURL(file)};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,avatar:state.avatar?'Аватар сохранён локально':null},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vasilisa-week-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('reset').onclick=()=>{state=fresh();selected=0;session=null;save();$('avatar').hidden=true;$('avatar').removeAttribute('src');$('avatarPlaceholder').hidden=false;renderReport();renderIntro()};
$('gazan').onclick=async()=>{if(audioEnabled)await toggleAudio();$('songPlayer').innerHTML='<iframe title="Gazan — 67 (Six Seven), официальный плеер Spotify" src="https://open.spotify.com/embed/track/7wdSCi9346RbeHjFsB6TFX?theme=0" width="100%" height="152" style="border:0;border-radius:12px" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>';$('songDialog').showModal()};
$('closeSong').onclick=()=>$('songDialog').close();$('songDialog').addEventListener('close',()=>{$('songPlayer').innerHTML=''});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&audioEnabled)toggleAudio()});
renderIntro();
